"""second migration

Revision ID: 0a2609ed2b6b
Revises: f380633efe61
Create Date: 2022-07-12 00:58:13.171644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2609ed2b6b'
down_revision = 'f380633efe61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
